// <auto-generated />
using System;
using BarClip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarClip.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250709001010_addedusers")]
    partial class addedusers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarClip.Data.Schema.OriginalVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrentTrimmedVideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("TrimFinish")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TrimStart")
                        .HasColumnType("time");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OriginalVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.TrimmedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("OriginalVideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalVideoId");

                    b.HasIndex("UserId");

                    b.ToTable("TrimmedVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BarClip.Data.Schema.OriginalVideo", b =>
                {
                    b.HasOne("BarClip.Data.Schema.User", "User")
                        .WithMany("OriginalVideos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarClip.Data.Schema.TrimmedVideo", b =>
                {
                    b.HasOne("BarClip.Data.Schema.OriginalVideo", "OriginalVideo")
                        .WithMany("TrimmedVideos")
                        .HasForeignKey("OriginalVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarClip.Data.Schema.User", "User")
                        .WithMany("TrimmedVideos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("OriginalVideo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BarClip.Data.Schema.OriginalVideo", b =>
                {
                    b.Navigation("TrimmedVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.User", b =>
                {
                    b.Navigation("OriginalVideos");

                    b.Navigation("TrimmedVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
