// <auto-generated />
using System;
using BarClip.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarClip.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250611045554_Trimmedvideofix1")]
    partial class Trimmedvideofix1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BarClip.Data.Schema.TrimmedVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OriginalVideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OriginalVideoId")
                        .IsUnique();

                    b.ToTable("TrimmedVideos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("TrimFinish")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TrimStart")
                        .HasColumnType("time");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("BarClip.Data.Schema.TrimmedVideo", b =>
                {
                    b.HasOne("BarClip.Data.Schema.Video", "OriginalVideo")
                        .WithOne("TrimmedVideo")
                        .HasForeignKey("BarClip.Data.Schema.TrimmedVideo", "OriginalVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalVideo");
                });

            modelBuilder.Entity("BarClip.Data.Schema.Video", b =>
                {
                    b.Navigation("TrimmedVideo");
                });
#pragma warning restore 612, 618
        }
    }
}
