<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-ios</TargetFrameworks>
		<OutputType>Exe</OutputType>
		<RootNamespace>BarClip.Maui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>BarClip</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.nathandamron.barclip.maui</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>4.0</ApplicationDisplayVersion>
		<ApplicationVersion>117</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">12.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">24.0</SupportedOSPlatformVersion>		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>
	<PropertyGroup Condition="$(TargetFramework.Contains('-ios'))">
		<CodesignEntitlements>Platforms/iOS/Entitlements.plist</CodesignEntitlements>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.png" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.png" Color="#FFFFFF" BaseSize="512,512" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />

		<MauiAsset Include="appsettings.json" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="4.1.2" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
		<PackageReference Include="Sentry.Maui" Version="6.1.0" />
		<PackageReference Include="SkiaSharp.Extended.UI.Maui" Version="2.0.0" />
		<PackageReference Include="Microsoft.Identity.Client" Version="4.83.3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\BarClip.Core\BarClip.Core.csproj" />
	  <ProjectReference Include="..\BarClip.Data\BarClip.Data.csproj" />
	  <ProjectReference Include="..\BarClip.Models\BarClip.Models.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Features\Camera\CameraPage.xaml.cs">
	    <DependentUpon>CameraPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Features\Sessions\SessionLibraryPage.xaml.cs">
	    <DependentUpon>SessionLibraryPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Features\Videos\VideoLibraryPage.xaml.cs">
	    <DependentUpon>VideoLibraryPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Features\Videos\VideoPlayerPage.xaml.cs">
	    <DependentUpon>VideoPlayerPage.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Features\Camera\CameraPageCameraPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="NewPage1.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Sessions\SessionLibraryPageSessionLibraryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Sessions\SessionPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Videos\VideoLibraryPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Features\Videos\VideoPlayerPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <None Update="appsettings.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>